language: node_js
os:
 - linux
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "iojs-v3"
  - "iojs-v2"
  - "iojs-v1"
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - 'nvm install-latest-npm'
install:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9" ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}"; else npm install; fi;'
script:
  - 'if [ -n "${PRETEST-}" ]; then npm run pretest ; fi'
  - 'if [ -n "${POSTTEST-}" ]; then npm run posttest ; fi'
  - 'if [ -n "${COVERAGE-}" ]; then npm run coverage ; fi'
  - 'if [ -n "${TEST-}" ]; then npm run tests-only ; fi'
sudo: false
env:
  global:
    - TEST=true
  matrix:
    - UGLIFY=2
    - UGLIFY=3
matrix:
  fast_finish: true
  include:
    - node_js: "node"
      env: PRETEST=true
    - node_js: "node"
      env: POSTTEST=true
    - node_js: "4"
      env: COVERAGE=true
    - node_js: "0.11"
      env: UGLIFY=2 TEST=true ALLOW_FAILURE=true
    - node_js: "0.11"
      env: UGLIFY=3 TEST=true ALLOW_FAILURE=true
    - node_js: "0.9"
      env: UGLIFY=2 TEST=true ALLOW_FAILURE=true
    - node_js: "0.9"
      env: UGLIFY=3 TEST=true ALLOW_FAILURE=true
    - node_js: "0.6"
      env: UGLIFY=2 TEST=true ALLOW_FAILURE=true
    - node_js: "0.6"
      env: UGLIFY=3 TEST=true ALLOW_FAILURE=true
    - node_js: "0.4"
      env: UGLIFY=2 TEST=true ALLOW_FAILURE=true
    - node_js: "0.4"
      env: UGLIFY=3 TEST=true ALLOW_FAILURE=true
  allow_failures:
    - env: UGLIFY=2 TEST=true ALLOW_FAILURE=true
    - env: UGLIFY=3 TEST=true ALLOW_FAILURE=true
